import {
  Activity,
  BarChart3,
  Bell,
  Bot,
  Box,
  Boxes,
  Brain,
  Cloud,
  Code,
  Container,
  Cpu,
  CreditCard,
  Database,
  FileText,
  Flag,
  Flame,
  Folder,
  GitBranch,
  Globe,
  HardDrive,
  Heart,
  Inbox,
  Key,
  Layers,
  Link,
  Lock,
  Mail,
  MapPin,
  MessageSquare,
  Monitor,
  Network,
  Package,
  PieChart,
  Plug,
  RefreshCw,
  Router,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShoppingCart,
  Smartphone,
  Star,
  Terminal,
  Timer,
  User,
  Users,
  Workflow,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { DiagramIconName } from '@/lib/fileIcons'

/** Icon name -> component, for the diagram node icon picker. */
export const DIAGRAM_ICONS: Record<DiagramIconName, LucideIcon> = {
  box: Box,
  server: Server,
  database: Database,
  cloud: Cloud,
  globe: Globe,
  user: User,
  users: Users,
  shield: Shield,
  lock: Lock,
  key: Key,
  cpu: Cpu,
  'hard-drive': HardDrive,
  layers: Layers,
  package: Package,
  terminal: Terminal,
  code: Code,
  'git-branch': GitBranch,
  workflow: Workflow,
  zap: Zap,
  activity: Activity,
  bell: Bell,
  mail: Mail,
  'message-square': MessageSquare,
  smartphone: Smartphone,
  monitor: Monitor,
  router: Router,
  network: Network,
  container: Container,
  boxes: Boxes,
  'file-text': FileText,
  folder: Folder,
  search: Search,
  settings: Settings,
  timer: Timer,
  'refresh-cw': RefreshCw,
  send: Send,
  inbox: Inbox,
  'credit-card': CreditCard,
  'shopping-cart': ShoppingCart,
  'bar-chart': BarChart3,
  'pie-chart': PieChart,
  brain: Brain,
  bot: Bot,
  flame: Flame,
  star: Star,
  heart: Heart,
  flag: Flag,
  'map-pin': MapPin,
  link: Link,
  plug: Plug,
}

export function diagramIcon(name: DiagramIconName): LucideIcon {
  return DIAGRAM_ICONS[name] ?? Box
}
