import { useEffect, useMemo, useRef, useState } from 'react'
import {
  AlertTriangle,
  BookOpen,
  Check,
  Copy,
  FileDown,
  Layers,
  Loader2,
  RefreshCw,
  Square,
} from 'lucide-react'
import { useStore } from '@/state/store'
import { basename, dirname, joinPath, relative } from '@/lib/paths'
import { cleanExplainMarkdown, explainFileName, type ExplainDepth } from '@/lib/explain'
import Markdown from './Markdown'

/**
 * The generated walkthrough: theory, system-design diagrams and a tutorial for
 * whichever file was open, rendered as it streams in.
 *
 * Mermaid fences are handed to the same renderer the Markdown preview uses, so
 * diagrams appear live and follow the active theme.
 */
export default function ExplainView({ path }: { path: string }) {
  const doc = useStore((s) => s.explain[path])
  const root = useStore((s) => s.root) ?? ''
  const bodyRef = useRef<HTMLDivElement>(null)
  const [pinnedToBottom, setPinnedToBottom] = useState(true)
  const [copied, setCopied] = useState(false)
  const [showThinking, setShowThinking] = useState(false)

  const running = doc?.status === 'running'

  // Follow the stream, but stop fighting the user the moment they scroll up.
  useEffect(() => {
    const el = bodyRef.current
    if (!el || !running || !pinnedToBottom) return
    el.scrollTop = el.scrollHeight
  }, [doc?.content, running, pinnedToBottom])

  // The document as the reader should see it: without whatever conversational
  // lead-in the CLI put in front of the first heading.
  const markdown = useMemo(() => cleanExplainMarkdown(doc?.content ?? ''), [doc?.content])

  const elapsed = useMemo(() => {
    if (!doc) return ''
    const end = doc.finishedAt ?? Date.now()
    return `${Math.max(1, Math.round((end - doc.startedAt) / 1000))}s`
  }, [doc?.startedAt, doc?.finishedAt, doc?.content])

  if (!doc) {
    return (
      <div className="empty-state">
        <span className="faint">Nothing generated for this file yet.</span>
      </div>
    )
  }

  const regenerate = (depth: ExplainDepth) => void useStore.getState().explainFile(path, depth)

  const saveMarkdown = async () => {
    const target = joinPath(dirname(path), explainFileName(basename(path)))
    await window.nova.fs.write(target, markdown)
    useStore.getState().bumpTree()
    await useStore.getState().openFile(target)
    useStore.getState().notify(`Saved ${relative(root, target)}`, 'success')
  }

  const copy = async () => {
    await navigator.clipboard.writeText(markdown)
    setCopied(true)
    setTimeout(() => setCopied(false), 1600)
  }

  return (
    <div className="explain-view">
      <div className="md-toolbar explain-toolbar">
        <BookOpen size={13} style={{ color: 'var(--accent)' }} />
        <b style={{ fontSize: 12.5 }}>{basename(path)}</b>
        <span className="faint" style={{ fontSize: 11 }}>
          {relative(root, path)}
        </span>

        <div className="segmented" style={{ marginLeft: 12 }}>
          <button
            className={doc.depth === 'file' ? 'active' : ''}
            onClick={() => regenerate('file')}
            disabled={running}
            title="Explain this file on its own"
          >
            <BookOpen size={12} /> This file
          </button>
          <button
            className={doc.depth === 'system' ? 'active' : ''}
            onClick={() => regenerate('system')}
            disabled={running}
            title="Read its imports, callers and tests too"
          >
            <Layers size={12} /> In context
          </button>
        </div>

        <span style={{ flex: 1 }} />

        <span className="chip" title={`Generated by ${doc.provider}`}>
          {doc.provider} · {elapsed}
        </span>

        {doc.thinking.trim() && (
          <button className="btn ghost sm" onClick={() => setShowThinking((v) => !v)}>
            {showThinking ? 'Hide' : 'Show'} reasoning
          </button>
        )}

        {running ? (
          <button className="btn sm" onClick={() => void useStore.getState().stopExplain(path)}>
            <Square size={11} /> Stop
          </button>
        ) : (
          <>
            <button className="btn sm" onClick={copy} disabled={!markdown}>
              {copied ? <Check size={12} /> : <Copy size={12} />} {copied ? 'Copied' : 'Copy'}
            </button>
            <button className="btn sm" onClick={() => void saveMarkdown()} disabled={!markdown}>
              <FileDown size={12} /> Save as Markdown
            </button>
            <button className="btn primary sm" onClick={() => regenerate(doc.depth)}>
              <RefreshCw size={12} /> Regenerate
            </button>
          </>
        )}
      </div>

      {doc.status === 'error' && (
        <div className="explain-error">
          <AlertTriangle size={13} />
          <span>{doc.error ?? 'The agent run failed.'}</span>
          <button className="btn sm" onClick={() => regenerate(doc.depth)}>
            <RefreshCw size={12} /> Try again
          </button>
        </div>
      )}

      {showThinking && doc.thinking.trim() && (
        <pre className="explain-thinking">{doc.thinking}</pre>
      )}

      <div
        className="explain-body md-preview"
        ref={bodyRef}
        onScroll={(e) => {
          const el = e.currentTarget
          setPinnedToBottom(el.scrollHeight - el.scrollTop - el.clientHeight < 80)
        }}
      >
        {markdown ? (
          <Markdown content={markdown} basePath={path} />
        ) : (
          <div className="explain-waiting">
            <Loader2 size={18} className="spin" style={{ color: 'var(--accent)' }} />
            <p>
              Reading{' '}
              <code>{relative(root, path)}</code>
              {doc.depth === 'system' ? ', its imports, callers and tests…' : '…'}
            </p>
            <p className="faint">
              The walkthrough streams in as it is written — theory first, then the
              diagrams, then the tutorial.
            </p>
          </div>
        )}
        {running && markdown && (
          <div className="explain-streaming">
            <Loader2 size={12} className="spin" /> still writing…
          </div>
        )}
      </div>
    </div>
  )
}
