import { useEffect, useMemo, useRef, useState } from 'react'
import {
  AlertTriangle,
  Check,
  Copy,
  FileDown,
  GraduationCap,
  List,
  Loader2,
  RefreshCw,
  Square,
} from 'lucide-react'
import { useStore } from '@/state/store'
import { basename, joinPath, relative } from '@/lib/paths'
import { cleanExplainMarkdown } from '@/lib/explain'
import {
  TUTORIAL_CHAPTERS,
  tutorialChapter,
  tutorialFileName,
  type TutorialChapterId,
} from '@/lib/tutorial'
import Markdown from './Markdown'

/**
 * The generated project walkthrough: stack, architecture, patterns, algorithms,
 * data, flows, security and pipeline — rendered as it streams in.
 *
 * Two things differ from `ExplainView`, and both come from the document being
 * long rather than page-sized: there is a contents rail built from the headings
 * that have arrived so far, so the reader can navigate a document that is still
 * being written; and the chapter picker is a real navigation control, because
 * one chapter at a time is the sane way to read this.
 */
export default function TutorialView() {
  const doc = useStore((s) => s.tutorial)
  const root = useStore((s) => s.root) ?? ''
  const providers = useStore((s) => s.providers)
  const bodyRef = useRef<HTMLDivElement>(null)
  const [pinnedToBottom, setPinnedToBottom] = useState(true)
  const [copied, setCopied] = useState(false)
  const [showThinking, setShowThinking] = useState(false)
  const [showContents, setShowContents] = useState(true)

  const running = doc?.status === 'running'

  // Follow the stream, but stop fighting the user the moment they scroll up.
  useEffect(() => {
    const el = bodyRef.current
    if (!el || !running || !pinnedToBottom) return
    el.scrollTop = el.scrollHeight
  }, [doc?.content, running, pinnedToBottom])

  const markdown = useMemo(() => cleanExplainMarkdown(doc?.content ?? ''), [doc?.content])

  // Built from the text rather than from the rendered DOM, so it updates with
  // every chunk instead of waiting for a re-render of the whole document.
  const contents = useMemo(() => headings(markdown), [markdown])

  const elapsed = useMemo(() => {
    if (!doc) return ''
    const end = doc.finishedAt ?? Date.now()
    return `${Math.max(1, Math.round((end - doc.startedAt) / 1000))}s`
  }, [doc?.startedAt, doc?.finishedAt, doc?.content])

  if (!doc) {
    return (
      <div className="empty-state">
        <span className="faint">No tutorial generated for this project yet.</span>
      </div>
    )
  }

  const chapter = tutorialChapter(doc.chapter)
  const generate = (id: TutorialChapterId) => void useStore.getState().generateTutorial(id, doc.provider)

  const saveMarkdown = async () => {
    const target = joinPath(root, 'docs', tutorialFileName(doc.chapter))
    await window.nova.fs.write(target, markdown)
    useStore.getState().bumpTree()
    await useStore.getState().openFile(target)
    useStore.getState().notify(`Saved ${relative(root, target)}`, 'success')
  }

  const copy = async () => {
    await navigator.clipboard.writeText(markdown)
    setCopied(true)
    setTimeout(() => setCopied(false), 1600)
  }

  const providerLabel = providers.find((p) => p.id === doc.provider)?.label ?? doc.provider

  return (
    <div className="explain-view tutorial-view">
      <div className="md-toolbar explain-toolbar">
        <GraduationCap size={13} style={{ color: 'var(--accent)' }} />
        <b style={{ fontSize: 12.5 }}>{basename(root) || 'Project'}</b>
        <span className="faint" style={{ fontSize: 11 }}>
          {chapter.short}
        </span>

        <button
          className={`btn ghost sm ${showContents ? 'active' : ''}`}
          style={{ marginLeft: 8 }}
          title="Toggle the contents rail"
          onClick={() => setShowContents((v) => !v)}
        >
          <List size={12} /> Contents
        </button>

        <span style={{ flex: 1 }} />

        <span className="chip" title={`Generated by ${providerLabel}`}>
          {providerLabel} · {elapsed}
        </span>

        {doc.thinking.trim() && (
          <button className="btn ghost sm" onClick={() => setShowThinking((v) => !v)}>
            {showThinking ? 'Hide' : 'Show'} reasoning
          </button>
        )}

        {running ? (
          <button className="btn sm" onClick={() => void useStore.getState().stopTutorial()}>
            <Square size={11} /> Stop
          </button>
        ) : (
          <>
            <button className="btn sm" onClick={copy} disabled={!markdown}>
              {copied ? <Check size={12} /> : <Copy size={12} />} {copied ? 'Copied' : 'Copy'}
            </button>
            <button
              className="btn sm"
              onClick={() => void saveMarkdown()}
              disabled={!markdown}
              title={`Write it into the project as docs/${tutorialFileName(doc.chapter)}`}
            >
              <FileDown size={12} /> Save into project
            </button>
            <button className="btn primary sm" onClick={() => generate(doc.chapter)}>
              <RefreshCw size={12} /> Regenerate
            </button>
          </>
        )}
      </div>

      <div className="tutorial-chapters">
        {TUTORIAL_CHAPTERS.map((entry) => (
          <button
            key={entry.id}
            className={`tutorial-chapter ${entry.id === doc.chapter ? 'active' : ''}`}
            disabled={running}
            title={entry.blurb}
            onClick={() => generate(entry.id)}
          >
            {entry.short}
          </button>
        ))}
      </div>

      {doc.status === 'error' && (
        <div className="explain-error">
          <AlertTriangle size={13} />
          <span>{doc.error ?? 'The agent run failed.'}</span>
          <button className="btn sm" onClick={() => generate(doc.chapter)}>
            <RefreshCw size={12} /> Try again
          </button>
        </div>
      )}

      {showThinking && doc.thinking.trim() && <pre className="explain-thinking">{doc.thinking}</pre>}

      <div className="tutorial-split">
        {showContents && contents.length > 0 && (
          <nav className="tutorial-toc">
            {contents.map((heading, index) => (
              <button
                key={`${heading.text}:${index}`}
                className={`tutorial-toc-item level-${heading.level}`}
                onClick={() => scrollToHeading(bodyRef.current, heading.text)}
                title={heading.text}
              >
                {heading.text}
              </button>
            ))}
            {running && <span className="faint tutorial-toc-more">writing…</span>}
          </nav>
        )}

        <div
          className="explain-body md-preview"
          ref={bodyRef}
          onScroll={(e) => {
            const el = e.currentTarget
            setPinnedToBottom(el.scrollHeight - el.scrollTop - el.clientHeight < 80)
          }}
        >
          {markdown ? (
            <Markdown content={markdown} basePath={joinPath(root, 'TUTORIAL.md')} />
          ) : (
            <div className="explain-waiting">
              <Loader2 size={18} className="spin" style={{ color: 'var(--accent)' }} />
              <p>
                Reading <code>{basename(root) || 'the project'}</code> to write{' '}
                <b>{chapter.title.toLowerCase()}</b>.
              </p>
              <p className="faint">
                {providerLabel} is exploring the tree, the manifest, the entry points and the
                tests. A full walkthrough takes a few minutes — it streams in as it is written,
                and keeps going if you switch tabs.
              </p>
            </div>
          )}
          {running && markdown && (
            <div className="explain-streaming">
              <Loader2 size={12} className="spin" /> still writing…
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

interface Heading {
  level: number
  text: string
}

/**
 * Pulls `##` and `###` headings out of the streamed Markdown for the contents
 * rail, skipping anything inside a fenced block — a `# comment` in an example
 * snippet is not a chapter.
 */
function headings(markdown: string): Heading[] {
  const found: Heading[] = []
  let inFence = false
  for (const line of markdown.split('\n')) {
    if (/^\s*```/.test(line)) {
      inFence = !inFence
      continue
    }
    if (inFence) continue
    const match = /^(#{2,3}) +(.+?)\s*$/.exec(line)
    if (match) found.push({ level: match[1].length, text: match[2].replace(/[*`]/g, '') })
  }
  return found
}

/**
 * Scrolls the rendered document to a heading by its text.
 *
 * Matching on text rather than on an id is deliberate: the Markdown renderer
 * does not mint anchors, and the document is still growing, so any id scheme
 * would have to be stable across re-renders of a changing document.
 */
function scrollToHeading(container: HTMLElement | null, text: string) {
  if (!container) return
  const target = Array.from(container.querySelectorAll('h1, h2, h3, h4')).find(
    (el) => (el.textContent ?? '').trim() === text.trim(),
  )
  target?.scrollIntoView({ block: 'start', behavior: 'smooth' })
}
