import { app, BrowserWindow, shell, ipcMain, nativeTheme } from 'electron'
import path from 'node:path'
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { registerFsHandlers } from './ipc/fs'
import { registerGitHandlers } from './ipc/git'
import { registerAiHandlers } from './ipc/ai'
import { registerShellHandlers } from './ipc/shell'
import { registerAppHandlers } from './ipc/app'
import { registerIndexerHandlers } from './ipc/indexer'
import { registerLspHandlers } from './ipc/lsp'
import { registerCoverageHandlers, registerTestHandlers } from './ipc/tests'
import { registerDebugHandlers } from './ipc/debug'
import { registerPluginHandlers } from './ipc/plugins'
import { registerHttpHandlers } from './ipc/http'
import { registerE2eHandlers } from './ipc/e2e'
import { registerSecurityHandlers } from './ipc/security'
import { registerShareHandlers } from './ipc/share'
import { registerDeviceHandlers } from './ipc/devices'
import { registerBuildHandlers } from './ipc/build'
import { installShutdownHandler, onShutdown } from './lib/shutdown'
import { registerStructuralHandlers } from './ipc/structural'
import { registerDatabaseHandlers } from './ipc/database'
import { registerProfileHandlers } from './ipc/profile'
import { registerInfraHandlers } from './ipc/infra'
import { registerChatHandlers } from './ipc/chats'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// The product name, set before `ready` because macOS reads it once to build the
// application menu — later and the menu bar keeps saying "Electron".
app.setName('Nova')

/**
 * Keep the settings directory where it already is.
 *
 * Electron derives `userData` from the application name, so renaming the app to
 * "Nova" silently moves it — and every existing install loses its settings,
 * chats, breakpoints, local history and installed plugins, which are simply
 * left behind in the old directory. Existing installs therefore keep the legacy
 * path; only a machine that has never run Nova gets the tidy new one.
 */
{
  const legacy = path.join(app.getPath('appData'), 'nova-ide')
  if (existsSync(legacy)) app.setPath('userData', legacy)
}

// Opt-in remote debugging, for driving the app from tests/automation. Off
// unless the env var is set, so normal runs never expose a port.
if (process.env.NOVA_DEBUG_PORT) {
  app.commandLine.appendSwitch('remote-debugging-port', process.env.NOVA_DEBUG_PORT)
}

process.env.APP_ROOT = path.join(__dirname, '..')
const VITE_DEV_SERVER_URL = process.env.VITE_DEV_SERVER_URL
const RENDERER_DIST = path.join(process.env.APP_ROOT, 'dist')

/**
 * The brand mark, generated by `scripts/make-icon.mjs`.
 *
 * A packaged build takes its icon from the bundle, so this is only needed for
 * the window (Windows/Linux) and for the dock while running from source —
 * without it a dev run shows Electron's own logo.
 */
const ICON_PNG = path.join(process.env.APP_ROOT, 'build', 'icon.png')

let mainWindow: BrowserWindow | null = null

/**
 * Whether a navigation stays where the app already is.
 *
 * `file:` URLs have a null origin, so the packaged build compares the directory
 * the app was loaded from instead — otherwise every in-app navigation would
 * look cross-origin and be refused.
 */
function sameOrigin(next: string, current: string): boolean {
  try {
    const a = new URL(next)
    const b = new URL(current)
    if (a.protocol === 'file:' && b.protocol === 'file:') {
      return path.dirname(a.pathname).startsWith(path.dirname(b.pathname))
    }
    return a.origin === b.origin
  } catch {
    return false
  }
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1600,
    height: 1000,
    minWidth: 900,
    minHeight: 600,
    show: false,
    title: 'Nova',
    icon: ICON_PNG,
    backgroundColor: '#111318',
    titleBarStyle: 'hiddenInset',
    trafficLightPosition: { x: 14, y: 14 },
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
      // Powers the built-in Chromium browser pane and the live UI preview.
      webviewTag: true,
      spellcheck: false,
    },
  })

  /*
   * Showing the window is deliberately belt-and-braces.
   *
   * `show: false` until `ready-to-show` avoids a flash of unpainted chrome, but
   * it makes the reveal depend on a single event — and when that event does not
   * arrive the app runs perfectly with its renderer loaded and simply never
   * appears, which is indistinguishable from a crash and much harder to
   * diagnose. That happened in a packaged build whose renderer had finished
   * loading and rendering.
   *
   * So: show on whichever signal arrives first, and fall back to a timer that
   * shows it regardless. A brief flash is a cosmetic problem; an invisible
   * editor is not a usable one.
   */
  const reveal = () => {
    if (!mainWindow || mainWindow.isDestroyed() || mainWindow.isVisible()) return
    mainWindow.show()
  }
  mainWindow.once('ready-to-show', reveal)
  mainWindow.webContents.once('did-finish-load', reveal)
  setTimeout(reveal, 4000)

  // Anything the app itself tries to open in a new window goes to the OS browser;
  // in-app browsing happens inside the <webview> pane instead.
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:/.test(url)) shell.openExternal(url)
    return { action: 'deny' }
  })

  // The main window is the privileged one: it holds the preload bridge and
  // every IPC channel behind it. `setWindowOpenHandler` covered new windows but
  // nothing covered navigating this one — a `window.location` assignment from a
  // dependency, or a dragged link, would have loaded a remote page into the
  // renderer that owns that bridge. Navigation away from the app's own origin
  // is refused and handed to the OS browser, where it belongs.
  mainWindow.webContents.on('will-navigate', (event, url) => {
    const current = mainWindow?.webContents.getURL() ?? ''
    if (sameOrigin(url, current)) return
    event.preventDefault()
    if (/^https?:/i.test(url)) void shell.openExternal(url)
  })

  mainWindow.webContents.on('will-attach-webview', (_event, webPreferences) => {
    // Guest pages must never get Node access.
    delete (webPreferences as { preload?: string }).preload
    webPreferences.nodeIntegration = false
    webPreferences.contextIsolation = true
  })

  // target=_blank inside the browser pane navigates in place rather than
  // spawning an OS window the user cannot see.
  mainWindow.webContents.on('did-attach-webview', (_event, guest) => {
    guest.setWindowOpenHandler(({ url }) => {
      if (/^https?:/.test(url)) guest.loadURL(url)
      return { action: 'deny' }
    })
  })

  if (VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(VITE_DEV_SERVER_URL)
  } else {
    mainWindow.loadFile(path.join(RENDERER_DIST, 'index.html'))
  }

  mainWindow.on('closed', () => {
    mainWindow = null
  })
}

function broadcast(channel: string, payload: unknown) {
  for (const win of BrowserWindow.getAllWindows()) {
    if (!win.isDestroyed()) win.webContents.send(channel, payload)
  }
}

app.whenReady().then(() => {
  nativeTheme.themeSource = 'dark'

  // Registered before anything that registers a teardown, so the first
  // `before-quit` is already the coordinated one.
  installShutdownHandler()

  // A packaged app gets its dock icon from the bundle; running from source it
  // is Electron's until we set it explicitly.
  if (process.platform === 'darwin' && !app.isPackaged) {
    try {
      app.dock?.setIcon(ICON_PNG)
    } catch {
      /* a missing icon must never stop the app from starting */
    }
  }

  const indexer = registerIndexerHandlers({ broadcast })
  const lsp = registerLspHandlers({ broadcast })
  const debugger_ = registerDebugHandlers({ broadcast })
  const plugins = registerPluginHandlers({ broadcast })
  onShutdown('language servers', () => lsp.dispose())
  onShutdown('debug adapters', () => debugger_.dispose())
  onShutdown('plugin hosts', () => plugins.dispose())

  registerAppHandlers({ broadcast, getWindow: () => mainWindow })
  registerFsHandlers({ broadcast, onFileChanged: indexer.onFileChanged })
  registerGitHandlers()
  registerTestHandlers({ broadcast })
  registerCoverageHandlers()
  // Plugin MCP servers are resolved per run, so the AI console asks for them
  // rather than caching a list that would go stale on enable/disable.
  registerAiHandlers({ broadcast, mcpServers: plugins.mcpServers })
  registerShellHandlers({ broadcast })
  registerHttpHandlers({ broadcast })
  registerE2eHandlers()
  registerSecurityHandlers({ broadcast })
  registerShareHandlers({ broadcast })
  registerDeviceHandlers({ broadcast })
  registerBuildHandlers()
  registerStructuralHandlers()
  registerDatabaseHandlers()
  registerProfileHandlers()
  registerInfraHandlers()
  registerChatHandlers()

  void plugins.start()

  ipcMain.handle('window:action', (_e, action: string) => {
    if (!mainWindow) return
    if (action === 'minimize') mainWindow.minimize()
    else if (action === 'maximize')
      mainWindow.isMaximized() ? mainWindow.unmaximize() : mainWindow.maximize()
    else if (action === 'close') mainWindow.close()
    else if (action === 'devtools') mainWindow.webContents.toggleDevTools()
  })

  createWindow()

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
