import { app, BrowserWindow, shell, ipcMain, nativeTheme } from 'electron'
import path from 'node:path'
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { registerFsHandlers } from './ipc/fs'
import { registerGitHandlers } from './ipc/git'
import { registerAiHandlers } from './ipc/ai'
import { registerShellHandlers } from './ipc/shell'
import { registerAppHandlers } from './ipc/app'
import { registerIndexerHandlers } from './ipc/indexer'
import { registerLspHandlers } from './ipc/lsp'
import { registerCoverageHandlers, registerTestHandlers } from './ipc/tests'
import { registerDebugHandlers } from './ipc/debug'
import { registerPluginHandlers } from './ipc/plugins'
import { registerHttpHandlers } from './ipc/http'
import { registerE2eHandlers } from './ipc/e2e'
import { registerSecurityHandlers } from './ipc/security'
import { registerShareHandlers } from './ipc/share'
import { registerDeviceHandlers } from './ipc/devices'
import { registerBuildHandlers } from './ipc/build'
import { registerStructuralHandlers } from './ipc/structural'
import { registerDatabaseHandlers } from './ipc/database'
import { registerProfileHandlers } from './ipc/profile'
import { registerInfraHandlers } from './ipc/infra'
import { registerChatHandlers } from './ipc/chats'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// The product name, set before `ready` because macOS reads it once to build the
// application menu — later and the menu bar keeps saying "Electron".
app.setName('Nova')

/**
 * Keep the settings directory where it already is.
 *
 * Electron derives `userData` from the application name, so renaming the app to
 * "Nova" silently moves it — and every existing install loses its settings,
 * chats, breakpoints, local history and installed plugins, which are simply
 * left behind in the old directory. Existing installs therefore keep the legacy
 * path; only a machine that has never run Nova gets the tidy new one.
 */
{
  const legacy = path.join(app.getPath('appData'), 'nova-ide')
  if (existsSync(legacy)) app.setPath('userData', legacy)
}

// Opt-in remote debugging, for driving the app from tests/automation. Off
// unless the env var is set, so normal runs never expose a port.
if (process.env.NOVA_DEBUG_PORT) {
  app.commandLine.appendSwitch('remote-debugging-port', process.env.NOVA_DEBUG_PORT)
}

process.env.APP_ROOT = path.join(__dirname, '..')
const VITE_DEV_SERVER_URL = process.env.VITE_DEV_SERVER_URL
const RENDERER_DIST = path.join(process.env.APP_ROOT, 'dist')

/**
 * The brand mark, generated by `scripts/make-icon.mjs`.
 *
 * A packaged build takes its icon from the bundle, so this is only needed for
 * the window (Windows/Linux) and for the dock while running from source —
 * without it a dev run shows Electron's own logo.
 */
const ICON_PNG = path.join(process.env.APP_ROOT, 'build', 'icon.png')

let mainWindow: BrowserWindow | null = null

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1600,
    height: 1000,
    minWidth: 900,
    minHeight: 600,
    show: false,
    title: 'Nova',
    icon: ICON_PNG,
    backgroundColor: '#111318',
    titleBarStyle: 'hiddenInset',
    trafficLightPosition: { x: 14, y: 14 },
    webPreferences: {
      preload: path.join(__dirname, 'preload.cjs'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
      // Powers the built-in Chromium browser pane and the live UI preview.
      webviewTag: true,
      spellcheck: false,
    },
  })

  mainWindow.once('ready-to-show', () => mainWindow?.show())

  // Anything the app itself tries to open in a new window goes to the OS browser;
  // in-app browsing happens inside the <webview> pane instead.
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (/^https?:/.test(url)) shell.openExternal(url)
    return { action: 'deny' }
  })

  mainWindow.webContents.on('will-attach-webview', (_event, webPreferences) => {
    // Guest pages must never get Node access.
    delete (webPreferences as { preload?: string }).preload
    webPreferences.nodeIntegration = false
    webPreferences.contextIsolation = true
  })

  // target=_blank inside the browser pane navigates in place rather than
  // spawning an OS window the user cannot see.
  mainWindow.webContents.on('did-attach-webview', (_event, guest) => {
    guest.setWindowOpenHandler(({ url }) => {
      if (/^https?:/.test(url)) guest.loadURL(url)
      return { action: 'deny' }
    })
  })

  if (VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(VITE_DEV_SERVER_URL)
  } else {
    mainWindow.loadFile(path.join(RENDERER_DIST, 'index.html'))
  }

  mainWindow.on('closed', () => {
    mainWindow = null
  })
}

function broadcast(channel: string, payload: unknown) {
  for (const win of BrowserWindow.getAllWindows()) {
    if (!win.isDestroyed()) win.webContents.send(channel, payload)
  }
}

app.whenReady().then(() => {
  nativeTheme.themeSource = 'dark'

  // A packaged app gets its dock icon from the bundle; running from source it
  // is Electron's until we set it explicitly.
  if (process.platform === 'darwin' && !app.isPackaged) {
    try {
      app.dock?.setIcon(ICON_PNG)
    } catch {
      /* a missing icon must never stop the app from starting */
    }
  }

  const indexer = registerIndexerHandlers({ broadcast })
  const lsp = registerLspHandlers({ broadcast })
  const debugger_ = registerDebugHandlers({ broadcast })
  const plugins = registerPluginHandlers({ broadcast })
  app.on('before-quit', () => {
    void lsp.dispose()
    void debugger_.dispose()
    void plugins.dispose()
  })

  registerAppHandlers({ broadcast, getWindow: () => mainWindow })
  registerFsHandlers({ broadcast, onFileChanged: indexer.onFileChanged })
  registerGitHandlers()
  registerTestHandlers({ broadcast })
  registerCoverageHandlers()
  // Plugin MCP servers are resolved per run, so the AI console asks for them
  // rather than caching a list that would go stale on enable/disable.
  registerAiHandlers({ broadcast, mcpServers: plugins.mcpServers })
  registerShellHandlers({ broadcast })
  registerHttpHandlers({ broadcast })
  registerE2eHandlers()
  registerSecurityHandlers({ broadcast })
  registerShareHandlers({ broadcast })
  registerDeviceHandlers({ broadcast })
  registerBuildHandlers()
  registerStructuralHandlers()
  registerDatabaseHandlers()
  registerProfileHandlers()
  registerInfraHandlers()
  registerChatHandlers()

  void plugins.start()

  ipcMain.handle('window:action', (_e, action: string) => {
    if (!mainWindow) return
    if (action === 'minimize') mainWindow.minimize()
    else if (action === 'maximize')
      mainWindow.isMaximized() ? mainWindow.unmaximize() : mainWindow.maximize()
    else if (action === 'close') mainWindow.close()
    else if (action === 'devtools') mainWindow.webContents.toggleDevTools()
  })

  createWindow()

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})
